### ISSUE TITLE
skulpin-app-winit build broken due to raw-window-handle version mismatch

### ISSUE THREAD

**Issue by andrew-pa** [aclysma/skulpin#110]
It would seem that the latest version of winit/raw_window_handle broke something inside of skulpin-app-winit. Relevant `Cargo.toml` line:
```toml
skulpin = { version = "*", features = ["winit-app","winit-latest"]}
```

Build output:
```
   Compiling skulpin-app-winit v0.14.1
error[E0277]: the trait bound `winit::window::Window: raw_window_handle::HasRawWindowHandle` is not satisfied
    --> /home/andrew/.cargo/registry/src/github.com-1ecc6299db9ec823/skulpin-app-winit-0.14.1/src/app.rs:223:54
     |
223  |         let renderer_result = renderer_builder.build(&window, window_extents);
     |                                                      ^^^^^^^ the trait `raw_window_handle::HasRawWindowHandle` is not implemented for `winit::window::Window`
     |
help: trait impl with same name found
    --> /home/andrew/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.0/src/window.rs:1039:1
     |
1039 | / unsafe impl HasRawWindowHandle for Window {
1040 | |     /// Returns a [`raw_window_handle::RawWindowHandle`] for the Window
1041 | |     ///
1042 | |     /// ## Platform-specific
...    |
1057 | |     }
1058 | | }
     | |_^
     = note: perhaps two different versions of crate `raw_window_handle` are being used?
     = help: the trait `raw_window_handle::HasRawWindowHandle` is implemented for `&'a T`
     = note: required because of the requirements on the impl of `HasRawWindowHandle` for `winit::window::Window`
     = note: required for the cast to the object type `dyn HasRawWindowHandle`
```

If you switch to the `winit-25` feature the build is successful. A quick grep says that the `Cargo.lock` file has both versions `0.3.4` and versions `0.4.3` of `raw-window-handle` in it, and I've also seen a `0.5.0`.

**Comment by aclysma** [comment]
Thanks for mentioning this, and I'm sorry I didn't see this earlier. The winit-latest feature is a "best effort" thing that is going to inevitably break due to upstream changes. It is provided to hopefully unblock someone when they want to use more recent code than this library is tested against and everything "happens" to be compatible. But the downside is that because it does not pin against any particular version of any code, it will inevitably break at some point.

I'm not maintaining this library anymore, so you will either need to stay on supported versions of downstream code (i.e. using a feature to select the specific supported upstream versions, such as winit-25) or fork this library.

Most of the complex stuff for working with vulkan was moved to an upstream crate (`rafx-api`) that I will continue to maintain, so it's actually not a lot of code, and doing so gives you full control of your render loop/frame update as well as your dependencies. So imo it's really not a bad outcome.

**Comment by andrew-pa** [comment]
Thank you for your response! Yeah that makes sense, I figured that was the case after reading some of the other issues. We ended up just doing the Skia setup ourselves with OpenGL (not great but good enough for our use) and as you say it was pretty easy and probably better for the long term. This was a great prototyping library though! Thanks!
