### ISSUE TITLE
MacOS: Minimizing/Maximizing window can cause unpredictable frame rate and unresponsiveness

### ISSUE THREAD

**Issue by buzmeg** [aclysma/skulpin#18]
When running the interactive example, the frame rates are bouncing all over the place.  This should not be.

Given that my present mode is "FIFO", the FPS should be locked to 60.  The FPS counter does not indicate that.

Something is off with the Vulkan semaphores or with the FPS counter.

System is OS X with Iris Graphics.

Thanks.

Present Mode:
```
[2019-11-16T02:22:30Z INFO  skulpin::renderer::debug_reporter] "Created VkDevice to run on GPU Intel(R) Iris(TM) Graphics 6100 with the following 1 Vulkan extensions enabled:\n\t\tVK_KHR_swapchain v70"
[2019-11-16T02:22:30Z INFO  skulpin::renderer::swapchain] Available present modes: [FIFO]
[2019-11-16T02:22:30Z DEBUG skulpin::renderer::swapchain] Swapchain extents chosen by surface capabilities (900 600)
[2019-11-16T02:22:30Z INFO  skulpin::renderer::swapchain] Surface format: SurfaceFormatKHR { format: B8G8R8A8_UNORM, color_space: SRGB_NONLINEAR }
[2019-11-16T02:22:30Z INFO  skulpin::renderer::swapchain] Present mode: FIFO
```

FPS Results:
```
[2019-11-16T02:22:40Z DEBUG skulpin::app::app] fps: 751.40344
[2019-11-16T02:22:41Z DEBUG skulpin::app::app] fps: 69.021996
[2019-11-16T02:22:42Z DEBUG skulpin::app::app] fps: 61.861435
[2019-11-16T02:22:43Z DEBUG skulpin::app::app] fps: 61.2828
[2019-11-16T02:22:44Z DEBUG skulpin::app::app] fps: 657.58234
[2019-11-16T02:22:45Z DEBUG skulpin::app::app] fps: 583.38837
[2019-11-16T02:22:46Z DEBUG skulpin::app::app] fps: 925.67053
```

**Comment by aclysma** [comment]
Thanks for reporting! I can reproduce this behavior by minimizing the window, or maximizing it to a new virtual desktop, and then switching away from it. In this case, the app becomes unresponsive. I agree this points to a problem with Vulkan synchronization primitives. It's possible #5 and/or #12 are related issues.

**Comment by aclysma** [comment]
Spent time looking at this today. No solution yet, but I want to post notes on what I looked at so far in case someone else wants to look:

I reviewed the synchronization code. It looks pretty similar to the MoltenVK example code:
  - Mine: https://github.com/aclysma/skulpin/blob/87146376da347d9cf1a4871248afa32b32ebcdbb/src/renderer/renderer.rs#L120
  - MoltenVK Example: https://pastebin.com/GB4HD1mE
  - (My code is based on the approach shown in Vulkan-tutorial: https://vulkan-tutorial.com/Drawing_a_triangle/Drawing/Rendering_and_presentation)

I asked around on the Rust discord community server and received some helpful suggestions:
 - It sounds like the gfx-rs team has had some trouble with MacOS swap chain handling, I was suggested to look here:
   - https://github.com/gfx-rs/gfx/blob/49caf3604eee68e6e4044e30fd976aec83bf2f8d/examples/quad/main.rs#L607-L619
   - https://github.com/gfx-rs/gfx/blob/49caf3604eee68e6e4044e30fd976aec83bf2f8d/examples/quad/main.rs#L886-L980

This does seem a bit different from the MoltenVK example (that is working properly for me.) This may be worth revisiting later if I get stuck.

Finally, I was referred to this issue in MoltenVK: https://github.com/KhronosGroup/MoltenVK/issues/742

There's a lot of info in that issue and issues referenced from it. I haven't had a chance to go through it all in detail yet, but will try using the latest MoltenVK sdk since it includes this PR: https://github.com/KhronosGroup/MoltenVK/pull/760

**Comment by aclysma** [comment]
After updating to 1.1.126.0, I can see this logging: Using MTLFence for Vulkan semaphores. Likely indicates that PR is in the build, so that's good. However, it crashes on the first call to acquire_next_image (vkAcquireNextImageKHR) with no validation output for what went wrong.

Reverting back to 1.1.121.1 fixes the crash. Will open an issue for MoltenVK.

**Comment by buzmeg** [comment]
I can confirm that minimizing the window on MoltenVK causes unstable frame rate.  I can also confirm that Ubuntu LTS 18.04 with Vulkan 1.1.121 does *NOT* have this issue.

**Comment by aclysma** [comment]
Thanks for the info. A couple weeks ago I was more suspicious that I was doing something wrong because of the mysterious crashes on windows/linux. But those were all caused by a logic error in selecting a queue family index and the fix seems to have fixed it for everyone that reported it. 

I’ve been keeping an eye on the crash issue I opened for MoltenVK, I’d really like to see if some of their recent changes to using MTLFence help. But for now, their release that has this change crashes, and someone else recently confirmed MoltenVK is crashing for them too in that issue.

I believe flutter is going to move to metal soon so the best long term solution might be to use metal instead of Vulkan on MacOS.

**Comment by aclysma** [comment]
The crash issue introduced with 1.1.126.0 is mostly mitigated by recent changes to queue family logic that make it highly likely queue family index 0 is chosen. In addition, I confirmed that the latest MoltenVK code fixes the crash.

Unfortunately this didn't seem to do anything for the original issue regarding frame rate stability when the application is minimized.

**Comment by aclysma** [comment]
I noticed after updating to the latest winit release, the lock-up that was occurring when either maximizing and switching virtual desktops, or minimizing the window, seems to be fixed. 🎉 

The frame rate doesn't lock to vsync if the app is off-screen, but I don't consider this to be "wrong" given that if the app isn't on the screen, there is no relevant vsync. Additionally, end-users should not rely on vsync rate because it will be different from computer to computer and even monitor to monitor on the same machine with multiple monitors of varying refresh rate.

If someone wants to get more fine-grained behaviors for slowing update/refresh rates, I would suggest they implement their own winit loop. winit provides some nice functionality for controlling update rate and waiting for window events. (ControlFlow:Wait, ControlFlow::WaitUntil) In addition, rendering will only happen as frequently as `window.request_redraw()` is called.

(The "app" abstraction is mostly there for prototyping and trying out the library. I'm open to exposing this in some way in the "app" use-case but only if it doesn't add complexity.)
