### ISSUE TITLE
Update to winit-0.20.0, which fixes a bug on X11

### ISSUE THREAD

**Issue by osa1** [aclysma/skulpin#39]
Originally discussed [here](https://github.com/Kethku/neovide/issues/27#issuecomment-579434027).

It turns out the bug is fixed between winit-0.20.0-alpha6 and winit-0.20.0, as can be seen in the [CHANGELOG entry](https://github.com/rust-windowing/winit/blob/master/CHANGELOG.md#0200-2020-01-05) (first item).

It'd be good to switch over to 0.20.0 and have this bug fixed in downstream that use skulpin, like neovide.

**Comment by osa1** [comment]
I have a patch, hoping to submit a PR today or tomorrow.

**Comment by aclysma** [comment]
Well that’s awkward. I have a branch winit_20 that I’ve been waiting to put in master because there was another bug introduced between alpha6 and 0.20.0 that produces mouse events with wrong coordinates on macOS. 

https://github.com/rust-windowing/winit/issues/1389

I suppose that branch could point to a git hash in the winit repo so that it works with both but I don’t want to publish until there is a published version of winit that includes the macOS fix.

**Comment by Kethku** [comment]
In the meantime to unblock folks, maybe I should make a branch of skulpin which swaps the winit dependency to a working git hash, and we can reconvene once winit makes a new release

**Comment by aclysma** [comment]
We could do this on the winit_20 branch if you like. I can accept a PR for it now or do it when I get home.

**Comment by Kethku** [comment]
I made a PR. I had to change a bunch of i32 to f64 due to a recent change in winit... Up to you if I solved it correctly.

**Comment by Kethku** [comment]
Ok after a bunch of testing, 0.20.0 crashes with any window manipulation on windows 10. So I'm going to hold off until that gets fixed. There is a PR which claims to fix the problem but i tried it and it still happens, so it may be a while.

https://github.com/rust-windowing/winit/pull/1422

**Comment by filnet** [comment]
The winit PR has one more crash fix for Windows 10. Should not crash anymore (crossing fingers).
Try it out.

**Comment by aclysma** [comment]
0.6.0, which is on wine 0.21, was published yesterday
